##################################################################
# 服务器
##################################################################
server:
    port: 9091
    tomcat:
        uri-encoding: UTF-8
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

#####################################
## Spring配置
#####################################
spring:
    #数据源配置
    datasource:
        #驱动名称
        driver-class-name: com.mysql.cj.jdbc.Driver
        #链接地址
        url: jdbc:mysql://localhost:3306/alice_game_db?characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
        #用户名
        username: root
        #密码
        password: root
#####################################
# 日志配置项
#####################################
logging:
    config: classpath:log/log-dev.xml
#####################################
## MyBatis配置
#####################################
mybatis:
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
#####################################
## Resource配置
#####################################
resource:
    # 资源根目录
    root: E:\ALICE_GAME_RES